# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_nnumber', models.IntegerField()),
                ('spouse_name', models.CharField(max_length=20)),
            ],
        ),
    ]
